### ISSUE TITLE
'--output-format=cypherl' seems broken

### ISSUE THREAD

**Issue by lomnido** [memgraph/mgconsole#69] opened 2024-01-30 08:58 UTC
Hello Memgraph's community,

can we look forward to 'cypherl' option in '--output-format' to gets working some time?
See this result on the latest Memgraph (2.14.0-1):
```
echo "match (n) return n;" | mgconsole --output-format=cypherl
Segmentation fault (core dumped)
```

While using: `mgconsole --output-format=csv`
everything works fine in every case.

There is no impact on this issue, just keeping current information about the status.

**Comment by katarinasupe** [comment] 2024-01-30 09:18
Thank you, @lomnido, for reporting this. I'll go ahead and verify it and compare different versions to get to proper prioritization tags and get back to you. 

Is this currently a blocker? Are you running Memgraph in production? Did this work for you in previous versions of Memgraph if you tried it?

**Comment by lomnido** [comment] 2024-01-30 09:52
@katarinasupe it seems working only if output is one column (with single type value?). It is also working for 'DUMP DATABASE'. Did not find any more cases where it is working so far.

It is not a blocker.
Do not know how was it in versions.

**Comment by katarinasupe** [comment] 2024-01-30 09:52
I can verify that if I create a node in an empty db with Memgraph 2.14 (using latest Platform image) with:
`CREATE (n:Person {name: "name"})`
and run 
`echo "match (n) return n;" | mgconsole --output-format=cypherl`
it returns nothing. I don't get Segmentation fault (can't reproduce that). I tried running:
`echo "match (n) return n;" | mgconsole --output-format=cypherl > data.cypherl`
to verify that nothing gets produced, and it is indeed an empty file. 

When running:
` echo "match (n) return n;" | mgconsole --output-format=csv`
I get
```
"n"
"(:Person {name: ""name""})"
```

@gitbuda is this expected (my guess is no) and if not, what is the actual issue here? Also, not sure why segmentation fault happened above, I can't reproduce it.

**Comment by lomnido** [comment] 2024-01-30 10:04
@katarinasupe steps to reproduce:
on empty DB:
```
create (n:N) set n.prop = 1 return n;
```
and now it segfaults:
```
echo "match (n) return (n);" | mgconsole --output-format=cypherl
Segmentation fault (core dumped)
```

**Comment by lomnido** [comment] 2024-01-30 11:18
This is strange. When I have completely remove Memgraph's db files and wipe database clean, the 'Segmentation fault (core dumped)' is no longer there. However on DB that was only upgraded to the latest Memgraph, there is.

So if anyone facing 'Segmentation fault (core dumped)' issue, the complete DB wipe and restore might help. I need to test this theory.

**Comment by lomnido** [comment] 2024-01-30 11:51
@katarinasupe finally have 'Segmentation fault (core dumped)' reproduced:
on clean DB:
```
create (a:N)-[r:I]->(b:n) return a,r,b;
```
and now it should throw Segmentation fault:
```
echo "match (n) return (n);" | mgconsole --output-format=cypherl

Segmentation fault (core dumped)
```
(There is also empty line before it)

**Comment by katarinasupe** [comment] 2024-01-30 11:55
@lomnido thank you so much for providing steps to reproduce. I can confirm that the steps you provided do lead to a segmentation fault.

**Comment by imilinovic** [comment] 2024-02-18 23:26
Looking at the code and the [PR](https://github.com/memgraph/mgconsole/pull/54/files) that added this it seems .cypherl format was only intended to be used for database export like this: 
```echo "DUMP DATABASE;" | mgconsole --output-format=cypherl > data.cypherl```
because it assumes that all the given objects are strings and it just outputs them.

I think it makes sense to make this more clear in the README and close the issue with that PR.
I don't know how important this is but we can open a separate issue to implement this either here (mgconsole) or as part of MAGE export_util (exporting a subgraph in cypherl format)
@katarinasupe

**Comment by lomnido** [comment] 2024-02-19 08:12
@imilinovic I see. Well in that case, the good practice is to throw a warning/error and not to segmentation fault, or am I wrong here as well?

**Comment by imilinovic** [comment] 2024-02-19 09:45
Yes I agree, that will be done.

**Comment by katarinasupe** [comment] 2024-02-19 12:12
@imilinovic I think it is okay to create a separate issue as a feature request on this repository for awareness and to have it in the backlog (link to this one as a source). @lomnido is definitely right that segmentation fault is not a good dev experience in this case.

**Closed** 2024-02-20 10:02 UTC
Labels: community, Severity - S3, Effort - Low, Importance - I1, Priority - Next

**Comment by lomnido** [comment] 2024-02-20 10:22
@imilinovic @katarinasupe Just git pulled, compiled and tested everywhere. Now it prints Error and not Segmentation Fault. Thanks everyone involved for help and support. :heart:
